swagger: "2.0"
info:
  version: "0.0.1"
  title: Hello World App
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /channels:
    # binds a127 app logic to a route
    x-swagger-router-controller: channels
    get:
      description: Returns 'channels' to the caller
      # used as the method name of the controller
      operationId: channels
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/ChannelsResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /blocks:
    # binds a127 app logic to a route
    x-swagger-router-controller: blocks
    get:
      description: Returns 'blocks' to the caller
      # used as the method name of the controller
      operationId: blocks
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/BlocksResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /transactions:
    # binds a127 app logic to a route
    x-swagger-router-controller: transactions
    get:
      description: Returns 'transactions' to the caller
      # used as the method name of the controller
      operationId: transactions
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/TransactionsResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  ChannelsResponse:
    required:
      - message
    properties:
      message:
        type: string
  BlocksResponse:
    required:
      - message
    properties:
      message:
        type: string
  TransactionsResponse:
    required:
      - message
    properties:
      message:
        type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
